- name: Deploy via SSH
  run: |
    echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > key.pem
    chmod 600 key.pem

    ssh -o StrictHostKeyChecking=no -i key.pem dev@20.197.45.185 << 'EOF'

      echo "🚀 Connected"

      cd ~/ci-cd || exit

      echo "📥 Updating code"
      git fetch origin
      git reset --hard origin/main

      echo "📦 Installing deps"
      pnpm install

      echo "🏗️ Build"
      pnpm run build

      echo "♻️ Restarting services"

      cd apps/web && pm2 restart fe-server

      cd ../http-server && pm2 restart http-server

      cd ../ws-server && pm2 restart ws-server

      echo "✅ Deployment Done"

    EOF
