name: Deploy (Main)

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem dev@20.197.45.185 << 'EOF'

            echo "🚀 Deployment Started"

            cd ~/ci-cd || exit

            echo "🧹 Cleaning old build"
            rm -rf apps/web/.next

            echo "📥 Updating code"
            git fetch origin
            git reset --hard origin/main

            echo "📦 Install pnpm if missing"
            if ! command -v pnpm &> /dev/null
            then
              npm install -g pnpm
            fi

            echo "📦 Installing dependencies"
            pnpm install

            echo "🏗️ Building project"
            pnpm run build

            echo "🛑 Stopping old processes"
            pm2 delete fe-server || true
            pm2 delete http-server || true
            pm2 delete ws-server || true

            echo "🚀 Starting fresh processes"

            cd apps/web
            pm2 start npm --name "fe-server" -- start

            cd ../http-server
            pm2 start npm --name "http-server" -- start

            cd ../ws-server
            pm2 start npm --name "ws-server" -- start

            echo "💾 Saving PM2"
            pm2 save

            echo "📊 PM2 Status"
            pm2 list

            echo "✅ Deployment Done"

          EOF
